[package]
name = "pipspeak"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.3.4", features = ["derive"] }
flate2 = "1.0.26"
fxread = "0.2.5"
hashbrown = "0.14.0"
yaml-rust = "0.4.5"
